." Man page for quad
.TH QUAD 1 "23 December 2014" "1.0" "User Commands"
.SH NAME
quadsolver -- solves the quadratic equation
.SH SYNOPSIS
.B quad
.I a b c
.SH DESCRIPTION
Quadsolver is a quadratic equation solver. The
.B quad
utility accepts 3 arguments which respectively correspond to the constants
.IR "a", 
.IR "b",
and
.I c
in a quadratic equation with the form
.I ax^2+bx+c.
.SH EXIT STATUS
The
.B quad
utility exits 0 on success, and 1 if an error occurs.
.SH AUTHORS
Dovi Salomon <Dovisal1@gmail.com>
