.\" Man page for quad
.Dd May 19, 2015
.Dt QUAD 1
.Os
.Sh NAME
.Nm quad
.Nd solves the quadratic equation
.Sh SYNOPSIS
.Nm
.Ar a b c
.Sh DESCRIPTION
The
.Nm
utility accepts 3 arguments which respectively correspond to the coefficients
.Ar "a", 
.Ar "b",
and
.Ar c
of a quadratic equation with the form
.Ar ax^2+bx+c.
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh AUTHOR
Dovi Salomon <Dovisal1@gmail.com>
